print("Vaso")
print("razmadze")
print("15 years old")
print("i live in Tbilisi")
print("my mother's name is Ia")
prin ("my father's name is Shmagi")
print("my brother's name is Nikolozi")
print("my grandfather's name is Vaso")
print("my grandmother's name is Mari")
print("my favorite car is M5 f90")
print("i am 10 in 10th grade")
print("i study 48 public school")
print("GOA")
print("i want became a ched")
print("my favorite food is cezari")
print("my favorite drink is water")
print("my favorite subject is math")
print("i like mobile game")
print("my village is in Gori")
print("my second village is in kaspi")